### 数据库配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/taco?serverTimezone=UTC
        username: taco
        password: taco
    
    jpa:
        open-in-view: false

### 数据库初始化脚本
#spring:
#   datasource:
#       schema:
#       - mysql-schema.sql
#       data:
#       - mysql-data.sql

### 日志配置
logging:
    level:
        root: WARN
        org:
            springframework:
                security: DEBUG

### 服务器配置
server:
    port: 8443
    ssl:
        key-store: 'classpath:taco.jks' 
        key-store-password: letmein
        key-password: letmein
